CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "ImportLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer,
    "SourceUrl" character varying(1000),
    "Marketplace" character varying(50),
    "Status" character varying(50) NOT NULL,
    "Message" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ImportLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "MercadoLibreTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" character varying(100),
    "AccessToken" text NOT NULL,
    "RefreshToken" text,
    "TokenType" character varying(50),
    "Scope" character varying(500),
    "ExpiresIn" integer,
    "ExpiresAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_MercadoLibreTokens" PRIMARY KEY ("Id")
);

CREATE TABLE "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SourceUrl" character varying(1000) NOT NULL,
    "SourceMarketplace" character varying(50) NOT NULL,
    "SourceProductId" character varying(150),
    "Title" character varying(500),
    "Description" text,
    "Brand" character varying(200),
    "Model" character varying(200),
    "SourcePrice" numeric,
    "SourceCurrency" character varying(10),
    "SourceStock" integer,
    "IsAvailable" boolean NOT NULL,
    "MLCategoryId" character varying(100),
    "MLItemId" character varying(100),
    "MLPrice" numeric,
    "MLStock" integer,
    "Status" character varying(50) NOT NULL,
    "ErrorMessage" text,
    "LastCheckedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
);

CREATE TABLE "ProductImages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "ImageUrl" character varying(1000) NOT NULL,
    "Position" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ProductImages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductImages_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ProductImages_ProductId" ON "ProductImages" ("ProductId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260511020436_InitialCreate', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "MercadoLibreTokens" ALTER COLUMN "Scope" TYPE text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260511040032_UpdateMercadoLibreTokenScopeLength', '8.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260511040451_AddMercadoLibreFieldsToProducts', '8.0.11');

COMMIT;

